[package]
name = "flip_cards"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rui = { workspace = true }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
rust_search = "2.0.0"
palette = "0.7.6"
enterpolation = "0.2"